from django.urls import path

from .views import (
    LoginAPIView,
    HoldingAPIView,
    SociedadAPIView,
    AdminAPIView, 
    PerfilesAPIView,
    ModulosWebAPIView,
    SubModulosWebAPIView,
    ModulosMovilAPIView,
    SubModulosMovilAPIView,
    UsuarioAPIViews,
    ClienteAPIView,
    AreaAPIView,
    CargoAPIView,
    EmpresaTransporteAPIView,
    VehiculosTransporteAPIView,
    ChoferesTransporteAPIView,
    SaludTrabajadoresAPIView,
    AFPTrabajadoresAPIView,
    PersonalTrabajadoresAPIView,
    CamposClientesAPIView,
    AreaClienteAPIView,
    CargoClienteAPIView,
    ContactoClienteAPIView,
    UnidadControlAPIView,
    LaboresAPIView,
    FolioComercialAPIView,
    CasasTrabajadoresAPIView,
    PersonalTrabajadoresMobileAPIView,
    EnviarDataProduccionAPIView,
    AreaAdministracionAPIView,
    CargoAdministracionAPIView,
    HorarioAPIView,
    ProduccionTrabajadorAPIView,
    CheckTokenSuperAdmin,
    CodigoQRAPIView,
    TrabajadoresCosechaQRView,
    CuadrillasAPIView,
    EnlaceAutoRegistroAPIView,
    ValidarEnlaceAutoRegistroAPIView,
    PersonalWebAPIView,
    PersonalForUserAPIView,
    SupervisorAPIView,
    JefesDeCuadrillaAPIView,
    APKLinkAPIView,
    ValidarApkLinkAPIView,
    DescargarApkAPIView,
    PersonalAsignadoAPIView,
    InformeRendimientoAPIView,
    VariablesDropDownInformePagoAPIView,
    InformePagoGenerarAPIView,
    InformePagoCSVAPIView,
    SociedadDetailAPIView,
    CuentaOrigenAPIView,
    BancoListAPIView,
    ProduccionPendienteAPIView,
    FiltrosProduccionAPIView,
    OpcionesFiltrosAPIView,
    ProcesarPagoAPIView,
    PagosRealizadosAPIView,
    FiltrosProduccionEfectivoAPIView,
    ProcesarPagoEfectivoAPIView,
    GenerarPlanillaEfectivoAPIView,
    TramosAPIView,
    FolioTransportistaAPIView,
    ConfirmarPagoTransportistaAPIView,
    PagoTransportistaAPIView,
    CalculoPagoTransportistaView,
    InformeTransportistaAPIView,
    GenerarProformaTransportistaAPIView,
    InformeDiasTrabajadosAPIView,
    DiasTrabajadosAprobadosAPIView,
    MesCerradoAPIView,
    HaberesAPIView,
    DescuentosAPIView,
    PersonalFiltradoAPIView,
    AsignarHaberesAPIView,
    AsignarDescuentosAPIView,
    GenerarLiquidacionesAPIView,
    GuardarContratoVariablesView,
    GenerarDocumentoView,
    CalibracionesListCreateView,
    CalibracionDetailView,
    GenerarPDFConCalibracionView,
    AjustarCalibracionView,
    LibroRemuneracionesElectronicoAPIView,
    GenerarDocumentosMasivoView,
    GenerarArchivoPreviewAPIView,
    FacturasCompraDistribucion,
    SociedadesUsuarioAPIView,
    CuentasAPIView,
    FacturasCompraAutomaticoAPIView,
    ServePDFFacturaSIIAPIView,
    DownloadPDFFacturaSIIAPIView,
    FacturasVentaAutomaticoAPIView,
    ServePDFFacturaVentaSIIAPIView,
    DownloadPDFFacturaVentaSIIAPIView,
    FacturasVentaDistribucion,
    ProcesarCartolaAPIView,
    MovimientosCartolaAPIView, 
    FacturasDistribuidasAPIView,
    RegistrarIngresoAPIView,
    CuentasOrigenPorBancoAPIView,
    MovimientoSaldosAPIView,
    FacturaEstadoAPIView,
    ProcesarCartolaEgresoAPIView,
    FacturasCompraDistribuidasAPIView,
    RegistrarEgresoAPIView,
    MovimientoEgresoSaldosAPIView,
    FacturaCompraEstadoAPIView,
    HistorialPagosAPIView,
    VerifyJWTAPIView,
    RefreshJWTAPIView,
)

app_name = 'contratista_test'

urlpatterns = [
    path('verify_superadmin_access/', CheckTokenSuperAdmin.as_view(), name='verify_superadmin_access'),
    path('verify_jwt/', VerifyJWTAPIView.as_view(), name='verify_jwt'),          # JWT (principal)
    path('refresh_jwt/', RefreshJWTAPIView.as_view(), name='refresh_jwt'),  
    path('api_login/', LoginAPIView.as_view(), name='api_login'),
    path('api_holding/', HoldingAPIView.as_view(),name='api_holding'),
    path('api_sociedad/', SociedadAPIView.as_view(), name='api_sociedad'),
    path('api_sociedad/<int:holding_id>/', SociedadAPIView.as_view(), name='api_sociedad_by_holding'),
    path('api_admin/', AdminAPIView.as_view(), name='api_admin'),
    path('api_perfil/<int:holding_id>/', PerfilesAPIView.as_view(), name='api_perfil_by_holding'),
    path('api_modulos_web/<int:holding_id>/', ModulosWebAPIView.as_view(), name='modulos-web-list'),
    path('api_submodulos_web/<int:holding_id>/', SubModulosWebAPIView.as_view(), name='submodulos-web-list'),
    path('api_modulos_movil/<int:holding_id>/', ModulosMovilAPIView.as_view(), name='modulos-movil-list'),
    path('api_submodulos_movil/<int:holding_id>/', SubModulosMovilAPIView.as_view(), name='submodulos-movil-list'),
    path('api_usuarios/', UsuarioAPIViews.as_view(), name='api_usuarios'),
    path('api_usuarios/<int:holding_id>/', UsuarioAPIViews.as_view(), name='api_usuarios_by_holding'),
    path('api_clientes/', ClienteAPIView.as_view(), name='api_cliente'),
    path('api_clientes/<int:holding_id>/', ClienteAPIView.as_view(), name='api_clientes_by_holding'),
    path('api_contactos_clientes/', ContactoClienteAPIView.as_view(), name='api_cliente'),
    path('api_contactos_clientes/<int:holding_id>/', ContactoClienteAPIView.as_view(), name='api_clientes_by_holding'),
    path('api_campos_clientes/<int:cliente_id>/', CamposClientesAPIView.as_view(), name='campos_clientes_list'),
    path('api_campos_clientes/', CamposClientesAPIView.as_view(), name='campos_clientes_create_update_delete'),
    path('api_areas/', AreaAPIView.as_view(), name='api_areas'),
    path('api_areas/<int:holding_id>/', AreaAPIView.as_view(), name='api_areas_by_holding'),
    path('api_cargos/', CargoAPIView.as_view(), name='api_cargos'),
    path('api_cargos/<int:holding_id>/', CargoAPIView.as_view(), name='api_cargos_by_holding'),
    path('api_areas_cliente/', AreaClienteAPIView.as_view(), name='api_areas'),
    path('api_areas_cliente/<int:holding_id>/', AreaClienteAPIView.as_view(), name='api_areas_by_holding'),
    path('api_cargos_cliente/', CargoClienteAPIView.as_view(), name='api_cargos'),
    path('api_cargos_cliente/<int:holding_id>/', CargoClienteAPIView.as_view(), name='api_cargos_by_holding'),
    path('api_areas_administracion/', AreaAdministracionAPIView.as_view(), name='api_areas'),
    path('api_areas_administracion/<int:holding_id>/', AreaAdministracionAPIView.as_view(), name='api_areas_by_holding'),
    path('api_cargos_administracion/', CargoAdministracionAPIView.as_view(), name='api_cargos'),
    path('api_cargos_administracion/<int:holding_id>/', CargoAdministracionAPIView.as_view(), name='api_cargos_by_holding'),
    path('api_empresa_transportes/', EmpresaTransporteAPIView.as_view(), name='api_empresa_transportes'),
    path('api_empresa_transportes/<int:holding_id>/', EmpresaTransporteAPIView.as_view(), name='api_empresa_transportes_by_holding'),
    path('api_vehiculos_transportes/', VehiculosTransporteAPIView.as_view(), name='api_vehiculos_transportes'),
    path('api_vehiculos_transportes/<int:holding_id>/', VehiculosTransporteAPIView.as_view(), name='api_vehiculos_transportes_by_holding'),
    path('api_choferes_transportes/', ChoferesTransporteAPIView.as_view(), name='api_choferes_transportes'),
    path('api_choferes_transportes/<int:holding_id>/', ChoferesTransporteAPIView.as_view(), name='api_choferes_transportes_by_holding'),
    path('api_salud_trabajadores/', SaludTrabajadoresAPIView.as_view(), name='api_salud_trabajadores'),
    path('api_salud_trabajadores/<int:holding_id>/', SaludTrabajadoresAPIView.as_view(), name='api_salud_trabajadores_by_holding'),
    path('api_afp_trabajadores/', AFPTrabajadoresAPIView.as_view(), name='api_afp_trabajadores'),
    path('api_afp_trabajadores/<int:holding_id>/', AFPTrabajadoresAPIView.as_view(), name='api_afp_trabajadores_by_holding'),
    path('api_casas_trabajadores/', CasasTrabajadoresAPIView.as_view(), name='api_casas_trabajadores'),
    path('api_casas_trabajadores/<int:holding_id>/', CasasTrabajadoresAPIView.as_view(), name='api_casas_trabajadores_by_holding'),
    path('api_personal/', PersonalTrabajadoresAPIView.as_view(), name='api_personal_trabajadores'),
    path('api_personal/<int:holding_id>/', PersonalTrabajadoresAPIView.as_view(), name='api_personal_trabajadores_by_holding'),
    path('unidad_control_comercial/', UnidadControlAPIView.as_view(), name='unidad_control_comercial'),
    path('unidad_control_comercial/<int:holding_id>/', UnidadControlAPIView.as_view(), name='unidad_control_comercial_by_holding'),
    path('labores_comercial/', LaboresAPIView.as_view(), name='labores_comercial'),
    path('labores_comercial/<int:holding_id>/', LaboresAPIView.as_view(), name='labores_comercial_by_holding'),
    path('folio_comercial/', FolioComercialAPIView.as_view(), name='labores_comercial'),
    path('folio_comercial/<int:holding_id>/', FolioComercialAPIView.as_view(), name='labores_comercial_by_holding'),
    path('personal_trabajadores_mobile/', PersonalTrabajadoresMobileAPIView.as_view(),name='personal_trabajadores_mobile'),
    path('data-produccion/<int:holding_id>/', EnviarDataProduccionAPIView.as_view(), name='data-produccion'),
    path('horarios/', HorarioAPIView.as_view(), name='horarios'),
    path('horarios/<int:holding_id>/', HorarioAPIView.as_view(), name='horarios_by_holding'),
    path('horarios/', HorarioAPIView.as_view(), name='horarios'),
    path('horarios/<int:holding_id>/', HorarioAPIView.as_view(), name='horarios_by_holding'),
    path('produccion-trabajador/', ProduccionTrabajadorAPIView.as_view(), name='horarios'),
    path('produccion-trabajador/<int:holding_id>/', ProduccionTrabajadorAPIView.as_view(), name='horarios_by_holding'),
    path('api_personal/', PersonalTrabajadoresAPIView.as_view(), name='api_personal_trabajadores'),
    path('api_personal/<int:holding_id>/', PersonalTrabajadoresAPIView.as_view(), name='api_personal_trabajadores_by_holding'),
    path('api_codigo_qr/', CodigoQRAPIView.as_view(), name='api_codigo_qr'),
    path('api_codigo_qr/<int:trabajador_id>/', CodigoQRAPIView.as_view(), name='api_codigo_qr_by_trabajador'),
    path('api_trabajadores_cosecha/', TrabajadoresCosechaQRView.as_view(), name='trabajadores_cosecha'),
    path('api_cuadrillas/grupos/', CuadrillasAPIView.as_view(), name='grupos_trabajadores'),
    path('api_cuadrillas/', CuadrillasAPIView.as_view(), name='api_cuadrillas'),
    path('enlaces-auto-registro/', EnlaceAutoRegistroAPIView.as_view(), name='enlaces_auto_registro'),
    path('validar-enlace/<str:token>/<int:id>/', ValidarEnlaceAutoRegistroAPIView.as_view(), name='validar_enlace'),
    path('personal-web/', PersonalWebAPIView.as_view(), name='personal-web'),
    path('api_personal_for_users/<int:holding_id>/', PersonalForUserAPIView.as_view(), name='personal-seleccion'),
    path('api_supervisores/', SupervisorAPIView.as_view(), name='api_supervisores'),
    path('api_supervisores/<int:holding_id>/', SupervisorAPIView.as_view(), name='api_supervisores_by_holding'),
    path('api_jefes_cuadrilla/', JefesDeCuadrillaAPIView.as_view(), name='api_jefes_cuadrilla'),
    path('api_jefes_cuadrilla/<int:holding_id>/', JefesDeCuadrillaAPIView.as_view(), name='api_jefes_cuadrilla_by_holding'),
    path('link_apk/<int:holding_id>/', APKLinkAPIView.as_view(), name='apk-link'),
    path('validate_apk/<str:token>/<int:id>/', ValidarApkLinkAPIView.as_view(), name='validar-apk-link'),
    path('download_apk/<str:token>/<int:id>/', DescargarApkAPIView.as_view(), name='descargar-apk'),
    path('api_personal_asignado/', PersonalAsignadoAPIView.as_view(), name='api_personal_asignado'),
    path('informe-rendimiento/', InformeRendimientoAPIView.as_view(), name='informe-rendimiento'),
    path('variables-dropdown-informe-pago/', VariablesDropDownInformePagoAPIView.as_view(), name='variables-dropdown-informe-pago'),
    path('informe-pago/generar/', InformePagoGenerarAPIView.as_view(), name='generar-informe-pago'),
    path('informe-pago/csv/', InformePagoCSVAPIView.as_view(), name='informe-pago-csv'),
    path('api_sociedades_modify/<int:holding_id>/', SociedadDetailAPIView.as_view(), name='api_sociedades_by_holding'),
    path('api_sociedades_modify/<int:holding_id>/<int:sociedad_id>/', SociedadDetailAPIView.as_view(), name='api_sociedad_detail'),
    path('api_cuentas_origen/<int:sociedad_id>/', CuentaOrigenAPIView.as_view(), name='api_cuentas_origen'),
    path('api_cuentas_origen/<int:sociedad_id>/<int:cuenta_id>/', CuentaOrigenAPIView.as_view(), name='api_cuenta_origen_detail'),
    path('api_bancos/', BancoListAPIView.as_view(), name='api_bancos'),
    path('produccion-pendiente/', ProduccionPendienteAPIView.as_view(), name='produccion-pendiente'),
    path('produccion-filtrada/', FiltrosProduccionAPIView.as_view(), name='produccion-filtrada'),
    path('opciones-filtros/<int:holding_id>/', OpcionesFiltrosAPIView.as_view(), name='opciones-filtros'),
    path('procesar-pago/', ProcesarPagoAPIView.as_view(), name='procesar-pago'),
    path('pagos-realizados/', PagosRealizadosAPIView.as_view(), name='transferencias-realizadas'),
    path('produccion-filtrada-efectivo/', FiltrosProduccionEfectivoAPIView.as_view(), name='produccion-filtrada-efectivo'),
    path('procesar-pago-efectivo/', ProcesarPagoEfectivoAPIView.as_view(), name='procesar-pago-efectivo'),
    path('generar-planilla-efectivo/', GenerarPlanillaEfectivoAPIView.as_view(), name='generar-planilla-efectivo'),
    path('api_tramos/', TramosAPIView.as_view(), name='tramos transporte'),
    path('api_tramos/<int:holding_id>/', TramosAPIView.as_view(), name='tramos transporte holding'),
    path('api_folio_transportista/', FolioTransportistaAPIView.as_view(), name='folio_transportista'), 
    path('api_folio_transportista/<int:holding_id>/', FolioTransportistaAPIView.as_view(), name='folio_transportista_by_holding'),
    path('confirmar-pago-transportista/', ConfirmarPagoTransportistaAPIView.as_view(), name='confirmar-pago-transportista'),
    path('pago-transportista/', PagoTransportistaAPIView.as_view(), name='pago_transportista'),
    path('pago-transportista/<int:id>/', PagoTransportistaAPIView.as_view(), name='pago_transportista_detail'),
    path('calculo-pago-transportista/', CalculoPagoTransportistaView.as_view(), name='calculo_pago_transportista'),
    path('informe-transportista/', InformeTransportistaAPIView.as_view(), name='informe-transportista'),
    path('generar-proformas/', GenerarProformaTransportistaAPIView.as_view(), name='generar-proformas'),
    path('generar-proformas/<int:proforma_id>/pdf/', GenerarProformaTransportistaAPIView.as_view(), name='descargar-pdf-proforma'),
    path('generar-proformas/<int:proforma_id>/', GenerarProformaTransportistaAPIView.as_view(), name='actualizar-proforma'),
    path('informe-dias-trabajados/', InformeDiasTrabajadosAPIView.as_view(), name='informe-dias-trabajados'),
    path('dias-trabajados-aprobados/', DiasTrabajadosAprobadosAPIView.as_view(), name='dias-trabajados-aprobados'),
    path('meses-cerrados/', MesCerradoAPIView.as_view(), name='meses-cerrados'),
    path('api_haberes/', HaberesAPIView.as_view(), name='api_haberes'),
    path('api_haberes/<int:holding_id>/', HaberesAPIView.as_view(), name='api_haberes_by_holding'),
    path('api_descuentos/', DescuentosAPIView.as_view(), name='api_descuentos'),
    path('api_descuentos/<int:holding_id>/', DescuentosAPIView.as_view(), name='api_descuentos_by_holding'),
    path('api_personal_filtrado/', PersonalFiltradoAPIView.as_view(), name='personal-filtrado'),
    path('api_asignar_haberes/', AsignarHaberesAPIView.as_view(), name='asignar-haberes'),
    path('api_asignar_descuentos/', AsignarDescuentosAPIView.as_view(), name='asignar-descuentos'),
    path('generar-liquidaciones/', GenerarLiquidacionesAPIView.as_view(), name='generar-liquidaciones'),
    path('api_guardar-documento-variables/', GuardarContratoVariablesView.as_view(), name='guardar_documento_variables'),
    path('api_generar-documento/', GenerarDocumentoView.as_view(), name='generar_documento'),
    path('api_calibraciones/<int:documento_id>/', CalibracionesListCreateView.as_view(), name='calibraciones_list'),
    path('api_calibraciones/', CalibracionesListCreateView.as_view(), name='calibracion_create'),
    path('api_calibracion/<int:calibracion_id>/', CalibracionDetailView.as_view(), name='calibracion_detail'),
    path('api_generar_pdf_calibrado/', GenerarPDFConCalibracionView.as_view(), name='generar_pdf_calibrado'),
    path('api_ajustar_calibracion/', AjustarCalibracionView.as_view(), name='ajustar_calibracion'),
    path('api_obtener-documento/<int:documento_id>/', GuardarContratoVariablesView.as_view(), name='obtener_documento'),
    path('api_listar-documentos/', GuardarContratoVariablesView.as_view(), name='listar_documentos'),
    path('generar-libro-remuneraciones/', LibroRemuneracionesElectronicoAPIView.as_view(), name='generar-libro-remuneraciones'),
    path('api_generar-documentos-masivo/', GenerarDocumentosMasivoView.as_view(), name='generar_documentos_masivo'),
    path('generar-archivo-previred/', GenerarArchivoPreviewAPIView.as_view(), name='generar-archivo-previred'),
    path('api_sociedades_usuario/<int:usuario_id>/', SociedadesUsuarioAPIView.as_view(), name='sociedades_usuario'),
    path('api_cuentas/', CuentasAPIView.as_view(), name='api_cuentas'),
    path('api_cuentas/<int:holding_id>/', CuentasAPIView.as_view(), name='api_cuentas_by_holding'),
    path('api_cuentas/update/<int:cuenta_id>/', CuentasAPIView.as_view(), name='api_cuenta_update'),
    path('api_cuentas/delete/<int:cuenta_id>/', CuentasAPIView.as_view(), name='api_cuenta_delete'),
    # URLs para Facturas Compra
    path('facturas_compra_automatico/', FacturasCompraAutomaticoAPIView.as_view(), name='facturas_compra_automatico'),
    path('facturas_sii_compra_distribuidas/', FacturasCompraDistribucion.as_view(), name='facturas_sii_distribuidas'),
    path('facturas_sii_pdf/<int:factura_id>/', ServePDFFacturaSIIAPIView.as_view(), name='serve_pdf_factura_sii'),
    path('facturas_sii_pdf_download/<int:factura_id>/', DownloadPDFFacturaSIIAPIView.as_view(), name='download_pdf_factura_sii'),
    # URLs para Facturas Venta
    path('facturas_venta_automatico/', FacturasVentaAutomaticoAPIView.as_view(), name='facturas_venta_automatico'),
    path('facturas_sii_venta_distribuidas/', FacturasVentaDistribucion.as_view(), name='facturas_sii_venta_distribuidas'),
    path('facturas_venta_sii_pdf/<int:factura_id>/', ServePDFFacturaVentaSIIAPIView.as_view(), name='serve_pdf_factura_venta_sii'),
    path('facturas_venta_sii_pdf_download/<int:factura_id>/', DownloadPDFFacturaVentaSIIAPIView.as_view(), name='download_pdf_factura_venta_sii'),
    # URLs para módulo de tesorería
    #Tesoreria-Ingresos
    path('tesoreria/procesar-cartola/', ProcesarCartolaAPIView.as_view(), name='procesar-cartola'),
    path('tesoreria/movimientos-cartola/', MovimientosCartolaAPIView.as_view(), name='movimientos-cartola'),
    path('tesoreria/facturas-distribuidas/', FacturasDistribuidasAPIView.as_view(), name='facturas-distribuidas'),
    path('tesoreria/registrar-ingreso/', RegistrarIngresoAPIView.as_view(), name='registrar-ingreso'),
    path('tesoreria/cuentas-origen/banco/<str:codigo_sbif>/', CuentasOrigenPorBancoAPIView.as_view()),
    path('tesoreria/movimientos-saldos/', MovimientoSaldosAPIView.as_view(), name='movimientos-saldos'),
    path('tesoreria/factura-estado/<int:factura_id>/', FacturaEstadoAPIView.as_view(), name='factura-estado'),
    #Tesoreria-Egresos
    path('tesoreria/procesar-cartola-egreso/', ProcesarCartolaEgresoAPIView.as_view(), name='procesar-cartola-egreso'),
    path('tesoreria/facturas-compra-distribuidas/', FacturasCompraDistribuidasAPIView.as_view(), name='facturas-compra-distribuidas'),
    path('tesoreria/registrar-egreso/', RegistrarEgresoAPIView.as_view(), name='registrar-egreso'),
    path('tesoreria/movimientos-egreso-saldos/', MovimientoEgresoSaldosAPIView.as_view(), name='movimientos-egreso-saldos'),
    path('tesoreria/factura-compra-estado/<int:factura_id>/', FacturaCompraEstadoAPIView.as_view(), name='factura-compra-estado'),
       # URLs para historial de pagos JSON
    path('historial/<str:tipo>/<str:estado>/', HistorialPagosAPIView.as_view(), name='historial-pagos'),
    # URLs para historial de pagos CSV
    path('historial/<str:tipo>/<str:estado>/csv/', HistorialPagosAPIView.as_view(), {'formato': 'csv'}, name='historial-pagos-csv'),
    
]   


